cc_library(
    name = "chapter02",
    hdrs = ["chapter02.h"],
)

cc_test(
    name = "chapter02_test",
    srcs = ["chapter02_test.c"],
    deps = [
        "@unity//:unity",
        ":chapter02",
    ],
)
