cc_library(
    name = "week1",
    srcs = ["week1.c"],
    hdrs = ["week1.h"],
)

cc_test(
    name = "week1_test",
    srcs = ["week1_test.c"],
    deps = [
        "@unity//:unity",
        ":week1",
    ],
)
