cc_library(
    name = "week3",
    srcs = ["week3.c"],
    hdrs = ["week3.h"],
)

cc_test(
    name = "week3_test",
    srcs = ["week3_test.c"],
    deps = [
        ":week3",
        "@unity",
    ],
)
